<?php

namespace Sesile\DelegationsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sesile\DelegationsBundle\Entity\Delegations;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelegationsRepository extends EntityRepository
{


    public function getUsersWhoHasMeAsDelegate($user)
    {

        $query = $this->createQueryBuilder('p')
            ->where('p.user = :user')
            ->setParameter('user', $user)
            ->andWhere('p.fin >= :fin')
            ->setParameter('fin', new \DateTime())
            ->andWhere('p.debut <= :debut')
            ->setParameter('debut', new \DateTime())
            ->getQuery();

        $delegations = $query->getResult();

        $users = array();

        foreach ($delegations as $deleg) {

            $users[] = $deleg->getDelegant();
        }

        return $users;

    }

    public function getUsersWhoHasMeAsDelegateRecursively($user)
    {
        $users = getUsersWhoHasMeAsDelegate($user);
        foreach ($users as $u) {

        }
    }


}
