<?php

namespace Sesile\MainBundle\Repository;

/**
 * CollectiviteOzwilloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectiviteOzwilloRepository extends \Doctrine\ORM\EntityRepository
{
}
