<?php

namespace Sesile\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentDetachedSignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentDetachedSignRepository extends EntityRepository
{
}
