<?php

namespace Sesile\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentHistoryRepository extends EntityRepository
{
}
