imports:
    - { resource: config_dev.yml }

be_simple_sso_auth:
    admin_sso:
        protocol:
            id: cas
            version: 2
        server:
            id: cas
            login_url: https://demosso.sictiam.fr/login
            logout_url: https://demosso.sictiam.fr/logout
            validation_url: https://demosso.sictiam.fr/serviceValidate

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sesiledemo
    database_user: root
    database_password: ***REMOVED***
    secret: ***REMOVED***
    cas_server: 172.17.100.43
    cas_port: 389
    cas_path: /
    cas_protocol: '2.0'
    ldap:
        dn_admin: cn=admin,dc=sictiam,dc=fr
        dn_user: cn=Users,dc=sictiam,dc=fr
        password: oP1U88zz