imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [secured_area]
    resource_owners:
        ozwillo:
            type:                ozwillo
            client_id:           2e771747-f906-4125-ba96-806553bc2ce2
            client_secret:       ***REMOVED***
            access_token_url:    https://accounts.ozwillo-preprod.eu/a/token
            authorization_url:   https://accounts.ozwillo-preprod.eu/a/auth
            infos_url:           https://accounts.ozwillo-preprod.eu/a/userinfo

parameters:
    domain: sesile-dev.local
    upload:
        path: '%kernel.root_dir%/../web/uploads/avatars/'
        signatures: '%kernel.root_dir%/../web/uploads/signatures/'
        logo_coll: '%kernel.root_dir%/../web/uploads/logo_coll/'
        msg_acc: '%kernel.root_dir%/../web/uploads/documents/msg_accueil.txt'
        fics: '%kernel.project_dir%/web/uploads/docs/'
    url_applet: signature.dev.sesile.fr
    ovh:
        environnement: demo.sesile
        zone: sictiam.fr
        target: dmzproxy.sictiam.fr.
    ozwillo_secret: )Ve*^e-JEr%d32g!-DV.x2s$oBwjr,|/
    email_sender_address: sictiam@sesile.fr

# Twig Configuration
twig:
    globals:
        only_office_url: 'http://localhost:8080/web-apps/apps/api/documents/api.js'