imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc



parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sesileprod
    database_user: root
    database_password: ***REMOVED***
    secret: ***REMOVED***
    cas_server: sso.sictiam.fr
    cas_port: 389
    cas_path: /
    cas_protocol: '2.0'
    ldap:
        dn_admin: cn=admin,dc=sictiam,dc=fr
        dn_user: cn=Users,dc=sictiam,dc=fr
        password: oP1U88zz


security:

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: true
            provider: webservice
            logout:
                success_handler: security.logout.success_handler
            cas:
                cas_server: sso.sictiam.fr
                cas_port: 443
                cas_path: /
                ca_cert_path: ~
                cas_protocol: '2.0'
                cas_mapping_attribute:
                check_path: /login_check

