imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    session:
            save_path: "%kernel.root_dir%/sessions/"

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'SesileMainBundle:Form:fields.html.twig'
    globals:
        upload_path: uploads/avatars/
        upload_path_logo: uploads/logo_coll/
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ SesileMainBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: mail
    host:      localhost

oneup_uploader:
    mappings:
        docs:
            frontend: custom
            custom_frontend:
                class: Sesile\DocumentBundle\Controller\DocumentUploader
                name: DocumentUploader
            use_orphanage: true

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    Sesile\UserBundle\Entity\User
    profile:
        form:
            type: sesile_user_profile


parameters:
    cas_server: sso.dev.sictiam.fr
    cas_port: 389
    cas_path: /
    cas_protocol: '2.0'
    gorg:
        path: %kernel.root_dir%/../vendor/gorg/phpcas/
    upload:
        path: %kernel.root_dir%/../web/uploads/avatars/
        fics: %kernel.root_dir%/../web/uploads/docs/
        logo_coll: %kernel.root_dir%/../web/uploads/logo_coll/
        msg_acc: %kernel.root_dir%/../web/uploads/documents/msg_accueil.txt
    ldap:
        dn_admin: cn=admin,dc=sictiam,dc=local
        dn_user: cn=Users,dc=sictiam,dc=local
        password: WcJa37BI
    domain_parse:
        default: sesile
        dbname: sictiam
    build:
        repository: "git@gitlab.sictiam.fr:sesile/sesile.git"
        branch: master
        commit: 994e6f7902355e6bf62dde14804e0bd9863d5662
        buildnumber: 1
    majorversion: 2

# La suite, c'est pour l'api
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    body_converter:
      enabled: true
    format_listener:
        rules:
            # setting fallback_format to json means that instead of considering the next rule in case of a priority mismatch, json will be used
            - { path: '^/api',  priorities: ['json', 'xml'],  prefer_extension: false }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    view:
        formats:
            rss: false
            xml: false
            json: true
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        view_response_listener: 'force'
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': 403
        messages:
            'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': true

nelmio_api_doc:
    name: Sesile API
    motd:
            template: SesileApiBundle::homedoc.html.twig

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

services:
    sesile.tokens.action_listener:
        class: Sesile\ApiBundle\EventListener\TokenListener
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    kernel.listener.route_listener:
        class: Sesile\MainBundle\EventListener\RouteListener
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onDomainParse }