imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
#    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
        migrator:
            type:  stream
            path:  '%kernel.logs_dir%/migrator-%kernel.environment%.log'
            level: debug
            channels: ['!security', '!doctrine']

assetic:
    use_controller: true

parameters:
    domain: '%sesile_domain%'
    upload:
        path: '%kernel.root_dir%/../web/uploads/avatars/'
        signatures: '%kernel.root_dir%/../web/uploads/signatures/'
        logo_coll: '%kernel.root_dir%/../web/uploads/logo_coll/'
        msg_acc: '%kernel.root_dir%/../web/uploads/documents/msg_accueil.txt'
        fics: '%kernel.project_dir%/web/uploads/docs/'
    url_applet: '%signature_url_applet%'

# Twig Configuration
twig:
    globals:
        only_office_url: '%only_office_url%'

swiftmailer:
    disable_delivery: true
