imports:
    - { resource: config.yml }

parameters:
    url_applet: '%signature_url_applet%'
    upload:
        path: '%kernel.root_dir%/../web/uploads/avatars/'
        fics: '%kernel.project_dir%/web/uploads/docs/'
        logo_coll: '%kernel.root_dir%/../web/uploads/logo_coll/'
        msg_acc: '%kernel.root_dir%/../web/uploads/documents/msg_accueil.txt'
        signatures: '%kernel.root_dir%/../web/uploads/signatures/'
monolog:
    handlers:
        main:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
            max_files: 10
        migrator:
            type:  rotating_file
            path:  '%kernel.logs_dir%/migrator-%kernel.environment%.log'
            level: info
            channels: ['!security', '!doctrine']
            max_files: 10
        logstash:
            type: gelf
            publisher:
                hostname: '%logstash_hostname%'
                port: 12201
            formatter: monolog.formatter.gelf_message