imports:
    - { resource: config_dev.yml }

hwi_oauth:
    firewall_names: [secured_area]
    use_referer: true
    resource_owners:
        ozwillo:
            type:                ozwillo
            client_id:           cb6cb63b-b904-490b-9a54-6782d6f127c8
            client_secret:       EB0MUa6wZZkRDlwP2rZFliJxV9vO2zma2swD90INUNI
            access_token_url:    https://accounts.ozwillo-preprod.eu/a/token
            authorization_url:   https://accounts.ozwillo-preprod.eu/a/auth
            infos_url:           https://accounts.ozwillo-preprod.eu/a/userinfo

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%-test'
        user:     '%database_user%'
        password: '%database_password%'

liip_functional_test: ~

swiftmailer:
    disable_delivery: true
parameters:
    domain: '%sesile_domain%'