imports:
    - { resource: config.yml }

hwi_oauth:
    firewall_names: [secured_area]
    resource_owners:
        ozwillo:
            type:                ozwillo
            client_id:           2e771747-f906-4125-ba96-806553bc2ce2
            client_secret:       ***REMOVED***

parameters:
#    domain: sesile.fr
#    database_driver: pdo_mysql
#    database_host: 127.0.0.1
#    database_port: null
#    database_name: sesileprod
#    database_user: root
#    database_password: ***REMOVED***
    secret: ***REMOVED***
    domain_parse:
        default: sesile
        dbname: sictiam
    ovh:
        environnement: ""
        zone: sesile.fr
        target: sesile.fr.
    email_sender_address: sictiam@sesile.fr
    url_applet: signature.sesile.fr
    upload:
        path: '%kernel.root_dir%/../web/uploads/avatars/'
        fics: '%kernel.project_dir%/web/uploads/docs/'
        logo_coll: '%kernel.root_dir%/../web/uploads/logo_coll/'
        msg_acc: '%kernel.root_dir%/../web/uploads/documents/msg_accueil.txt'
        signatures: '%kernel.root_dir%/../web/uploads/signatures/'
    ovh_credential:
        application: ***REMOVED***
        secret: ***REMOVED***
        consumer_key: ***REMOVED***
monolog:
    handlers:
        main:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
        migrator:
            type:  stream
            path:  '%kernel.logs_dir%/migrator-%kernel.environment%.log'
            level: info
            channels: ['!security', '!doctrine']