imports:
    - { resource: config.yml }

be_simple_sso_auth:
    admin_sso:
        protocol:
            id: cas
            version: 2
        server:
            id: cas
            login_url: https://sso.sictiam.fr/login
            logout_url: https://sso.sictiam.fr/logout
            validation_url: https://sso.sictiam.fr/serviceValidate

parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sesileprod
    database_user: root
    database_password: ***REMOVED***
    secret: ***REMOVED***
    cas_server: sso.sictiam.fr
    cas_port: 389
    cas_path: /
    cas_protocol: '2.0'
    ldap:
        dn_admin: cn=admin,dc=sictiam,dc=fr
        dn_user: cn=Users,dc=sictiam,dc=fr
        password: oP1U88zz
    domain_parse:
        default: sesile
        dbname: sictiam
    ovh:
        environnement: ""
        zone: sesile.fr
        target: sesile.fr.
    email_sender_address: sictiam@sesile.fr
    url_applet: signature.sesile.fr
    upload:
        path: %kernel.root_dir%/../web/uploads/avatars/
        fics: %kernel.root_dir%/../web/uploads/docs/
        logo_coll: %kernel.root_dir%/../web/uploads/logo_coll/
        msg_acc: %kernel.root_dir%/../web/uploads/documents/msg_accueil.txt
        signatures: %kernel.root_dir%/../web/uploads/signatures/
    majorversion: 3
    ovh_credential:
        application: ***REMOVED***
        secret: ***REMOVED***
        consumer_key: ***REMOVED***
