imports:
    - { resource: config_dev.yml }

hwi_oauth:
    firewall_names: [secured_area]
    resource_owners:
        ozwillo:
            type:                ozwillo
            client_id:           cb6cb63b-b904-490b-9a54-6782d6f127c8
            client_secret:       EB0MUa6wZZkRDlwP2rZFliJxV9vO2zma2swD90INUNI
            access_token_url:    https://accounts.ozwillo-preprod.eu/a/token
            authorization_url:   https://accounts.ozwillo-preprod.eu/a/auth
            infos_url:           https://accounts.ozwillo-preprod.eu/a/userinfo

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver_test%'
        host:     '%database_host_test%'
        port:     '%database_port_test%'
        dbname:   '%database_name_test%'
        user:     '%database_user_test%'
        password: '%database_password_test%'
        charset:  UTF8

liip_functional_test: ~

swiftmailer:
    disable_delivery: true
parameters:
    domain: sesile.fr
    database_driver: pdo_mysql
    database_host: '%database_host_test%'
    database_port: null
    database_name: '%database_name_test%'
    database_user: '%database_user_test%'
    database_password: '%database_password_test%'
    secret: ***REMOVED***