imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: '%locale%' }
    secret:          '%secret%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  fr
    session:         ~
    fragments:       ~
    http_method_override: true
    session:
        save_path: "%kernel.root_dir%/sessions/"
    assets:
      json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'
    serializer:
      enabled: false
# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        upload_path: uploads/avatars/
        upload_path_logo: uploads/logo_coll/
        upload_path_docs: /uploads/docs/
        upload_path_signatures: /uploads/signatures/
        sesile_version: 3.5
        id_video_yt: 'ms-YYoaU4PE'
#        only_office_url: 'https://office.sictiam.fr/web-apps/apps/api/documents/api.js'
        only_office_url: '%only_office_url%'
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

stof_doctrine_extensions:
    default_locale: fr
    orm:
        default:
            sluggable: true

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    bundles:        [ SesileMainBundle ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                connection: default
                auto_mapping: true

# Ozwillo Oauth2
hwi_oauth:
    firewall_names: [secured_area]
    resource_owners:
        ozwillo:
            type:                ozwillo
            client_id:           2e771747-f906-4125-ba96-806553bc2ce2
            client_secret:       ***REMOVED***

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    port:      25
#    transport: mail
#    host:      localhost

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    Sesile\UserBundle\Entity\User
    profile:
        form:
            type: Sesile\UserBundle\Form\Type\ProfileFormType
    from_email:
        address: sesile@sictiam.fr
        sender_name: SESILE

parameters:
    domain: '%sesile_domain%'
    informations:
        version: 4.0-sprint11
        contact_link: http://support.sictiam.fr/declarer-un-incident/
        id_yt_video: '%id_yt_video%'
    upload:
        path: '%kernel.project_dir%/web/uploads/avatars/'
        fics: '%kernel.project_dir%/web/uploads/docs/'
        logo_coll: '%kernel.project_dir%/web/uploads/logo_coll/'
        msg_acc: '%kernel.root_dir%/../web/uploads/documents/msg_accueil.txt'
        signatures: '%kernel.root_dir%/../web/uploads/signatures/'
    build:
        repository: "git@gitlab.sictiam.fr:sesile/sesile.git"
        branch: master
        commit: 994e6f7902355e6bf62dde14804e0bd9863d5662
        buildnumber: 0
    majorversion: 4
    url_applet: '%signature_url_applet%'
    ozwillo_portal: portal.ozwillo-preprod.eu
    ovh_credential:
        application: ***REMOVED***
        secret: ***REMOVED***
        consumer_key: ***REMOVED***
    hwi_oauth.authentication.provider.oauth.class: Sesile\UserBundle\Security\OAuthProvider
    contact: '%contact_email%'
# La suite, c'est pour l'api
fos_rest:
    serializer:
        serialize_null:  true
    routing_loader:
        include_format: false
    param_fetcher_listener: true
    body_listener: true
    access_denied_listener:
        # all requests using the 'json' format will return a 403 on an access denied violation
        json: true
    body_converter:
        enabled: false
    format_listener:
        rules:
            # setting fallback_format to json means that instead of considering the next rule in case of a priority mismatch, json will be used
            - { path: '^/api/v4/',  priorities: ['json'], fallback_format: 'json',  prefer_extension: false }
            - { path: '^/api/',  priorities: ['json'],  prefer_extension: false }
            - { path: '^/apirest/',  priorities: ['json'], fallback_format: 'json',  prefer_extension: false }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: false }
            - { path: '^/doc/download_sign', priorities: [ 'pdf' ], fallback_format: ~, prefer_extension: true }
    view:
        formats:
            rss: false
            xml: false
            json: true
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        view_response_listener: 'force'
    exception:
        enabled: true
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': 403
        messages:
            'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': true

fos_js_routing:
    routes_to_expose: [ list_classeur_api, get_classeur_api, isauthenticated_user_api, list_etapeclasseur_api ]

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"

nelmio_api_doc:
    name: Sesile API
    motd:
        template: SesileApiBundle::homedoc.html.twig

sensio_framework_extra:
    view:    { annotations: true }
    router:  { annotations: true }
    request: { converters: true }

sesile_migration:
    ozwillo_user_gateway: "%ozwillo_user_gateway_uri%"
    ozwillo_user_gateway_username: "%ozwillo_user_gateway_username%"
    ozwillo_user_gateway_password: "%ozwillo_user_gateway_password%"

services:
    my.sesile.user_provider:
        autowire: true
        autoconfigure: true
        class: Sesile\UserBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { ozwillo: email }]

    sesile.tokens.action_listener:
        class: Sesile\ApiBundle\EventListener\TokenListener
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    sesile.command.delayed_classeurs:
        class: Sesile\UserBundle\Command\NotificationDelayedClasseurCommand
        tags:
            -  { name: console.command }
        arguments: ["@monolog.logger.request","@doctrine.orm.entity_manager" , '@service_container', '@mailer']
    Sesile\ClasseurBundle\Service\ActionMailer:
        autowire: true
        autoconfigure: true
        public: true
        arguments:
            $fromEmail: '%email_sender_address%'
            $paths: '%upload%'