SesileUserBundle_admin_sesile_user_bundle_sesileUserAdmin:
    resource: "@SesileUserBundle/Controller/SesileUserAdmin/"
    type:     admingenerator
    prefix:   /admin/sesile_user_bundle/sesileUserAdmin


sesile_circuit:
    resource: "@SesileCircuitBundle/Controller/"
    type:     annotation
    prefix:   /circuit/

sesile_document:
    resource: "@SesileDocumentBundle/Controller/"
    type:     annotation
    prefix:   /doc/

sesile_classeur:
    resource: "@SesileClasseurBundle/Controller/"
    type:     annotation
    prefix:   /classeur/


sesile_main:
    resource: "@SesileMainBundle/Controller/"
    type:     annotation
    prefix:   /

sesile_users:
    resource: "@SesileUserBundle/Controller"
    type: annotation

_default:
    pattern: /

oneup_uploader:
    resource: .
    type: uploader

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"