sesile_main:
    resource: "@SesileMainBundle/Controller/"
    type:     annotation
    prefix:   /

sesile_tableau-de-bord:
    defaults: { _controller: SesileMainBundle:Default:app, reactRouting: null }
    path: /tableau-de-bord/{reactRouting}
    requirements:
        reactRouting: ".+"

sesile_classeurs:
    defaults: { _controller: SesileMainBundle:Default:app, reactRouting: null }
    path: /classeurs/{reactRouting}
    requirements:
        reactRouting: ".+"

sesile_classeur:
    defaults: { _controller: SesileMainBundle:Default:app, reactRouting: null }
    path: /classeur/{reactRouting}
    requirements:
        reactRouting: ".+"

sesile_utilisateur:
    defaults: { _controller: SesileMainBundle:Default:app, reactRouting: null }
    path: /utilisateur/{reactRouting}
    requirements:
        reactRouting: ".+"

sesile_documentations:
    defaults: { _controller: SesileMainBundle:Default:app, reactRouting: null }
    path: /documentations/{reactRouting}
    requirements:
        reactRouting: ".+"

sesile_admin:
    defaults: { _controller: SesileMainBundle:Default:app, reactRouting: null }
    path: /admin/{reactRouting}
    requirements:
        reactRouting: ".+"

sesile_document:
    resource: "@SesileDocumentBundle/Controller/"
    type:     annotation
#    prefix:   /doc/

sesile_api:
    resource: "@SesileApiBundle/Controller/"
    type:     annotation
    prefix:   /api/

#sesile_delegations:
#    resource: "@SesileDelegationsBundle/Controller/"
#    type:     annotation
#    prefix:   /delegation/

#sesile_circuit:
#    resource: "@SesileCircuitBundle/Controller/"
#    type:     annotation
#    prefix:   /circuit/

#sesile_document:
#    resource: "@SesileDocumentBundle/Controller/"
#    type:     annotation
#    prefix:   /doc/

#sesile_classeur:
#    resource: "@SesileClasseurBundle/Controller/ClasseurController.php"
#    type:     annotation
#    prefix:   /classeur/

sesile_classeur_api:
    resource: "@SesileClasseurBundle/Controller/"
    type:     annotation

sesile_users:
    resource: "@SesileUserBundle/Controller/"
    type: annotation

#sesile_security:
#    resource: "@SesileMainBundle/Resources/config/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

login:
    path:   /tableau-de-bord

login_check:
    path:   /login_check

logout:
    path:   /logout


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
