sesile_main:
    resource: "@SesileMainBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

sesile_classeur:
    defaults: { _controller: SesileMainBundle:Default:app, reactRouting: null }
    path: /classeur/{reactRouting}
    requirements:
        reactRouting: ".+"

sesile_api:
    resource: "@SesileApiBundle/Controller/"
    type:     annotation
    prefix:   /api/

#sesile_delegations:
#    resource: "@SesileDelegationsBundle/Controller/"
#    type:     annotation
#    prefix:   /delegation/

#sesile_circuit:
#    resource: "@SesileCircuitBundle/Controller/"
#    type:     annotation
#    prefix:   /circuit/

#sesile_document:
#    resource: "@SesileDocumentBundle/Controller/"
#    type:     annotation
#    prefix:   /doc/

#sesile_classeur:
#    resource: "@SesileClasseurBundle/Controller/ClasseurController.php"
#    type:     annotation
#    prefix:   /classeur/

sesile_classeur_api:
    resource: "@SesileClasseurBundle/Controller/"
    type:     annotation

sesile_type_classeur_api:
    resource: "@SesileClasseurBundle/Controller/TypeClasseurApiController.php"
    type:     rest

sesile_user_api:
    resource: "@SesileUserBundle/Controller/UserApiController.php"
    type:     rest
    prefix:   /apirest/users

#sesile_users:
#    resource: "@SesileUserBundle/Controller/"
#    type: annotation
#    prefix: /user

_default:
    path: /

oneup_uploader:
    resource: .
    type: uploader

#sesile_security:
#    resource: "@SesileMainBundle/Resources/config/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

login:
    path:   /login_check

login_check:
    path:   /login_check

logout:
    path:   /logout


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
