# app/config/security.yml
jms_security_extra:
    secure_all_services: true
    expressions: false

security:
    encoders:
        Sesile\UserBundle\Entity\User: sha512

    providers:
        webservice:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: true
            provider: webservice
            logout:
                success_handler: security.logout.success_handler
            cas:
                cas_server: sso.dev.sictiam.fr
                cas_port: 443
                cas_path: ~
                ca_cert_path: ~
                cas_protocol: S1
                cas_mapping_attribute:
                check_path: /login_check