# app/config/security.yml

security:
    encoders:
        Sesile\UserBundle\Entity\User: sha512

    providers:
        webservice:
            id: fos_user.user_provider.username
    firewalls:
        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            pattern:  ^/(_wdt|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: true
            provider: webservice
            logout: ~
            oauth:
                resource_owners:
                    ozwillo:  "/login/check-ozwillo"
                login_path:   /
                use_forward:  false
                failure_path: /
                oauth_user_provider:
                    service: my.sesile.user_provider

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/choix-collectivite, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/web/uploads/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/doc/uploadfile, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/doc/notifymodif, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/doc/downloadJWS, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc/uploaddocument, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc/uploadonly, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/classeur/valider_classeur_jws, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/classeur/liste-classeurs-admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/classeur/liste_admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/apirest/users/isauthenticated, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/apirest/document/only-office, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tableau-de-bord, roles: ROLE_USER }
        - { path: ^/collectivite, roles: ROLE_SUPER_ADMIN }
        - { path: ^/mailing, roles: ROLE_SUPER_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/preferences/message, roles: ROLE_ADMIN }
        - { path: ^/preferences/notifications, roles: ROLE_ADMIN }
