# app/config/security.yml
jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Sesile\UserBundle\Entity\User: sha512

    providers:
        webservice:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: true
            provider: webservice
            logout:
                success_handler: security.logout.success_handler
            cas:
                cas_server: sso.dev.sictiam.fr
                cas_port: 443
                cas_path: /
                ca_cert_path: ~
                cas_protocol: '2.0'
                cas_mapping_attribute:
                check_path: /login_check
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    access_control:
        - { path: ^/doc/uploadfile, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/doc/notifymodif, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/circuit, roles: ROLE_USER }
        - { path: ^/classeur, roles: ROLE_USER }
        - { path: ^/doc, roles: ROLE_USER }