# app/config/security.yml

security:
    encoders:
        Sesile\UserBundle\Entity\User: sha512

    providers:
        webservice:
            id: fos_user.user_provider.username
    firewalls:
        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            pattern:  ^/(_wdt|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: true
            provider: webservice
            trusted_sso:
                manager: admin_sso
                provider: webservice
                login_action: false #BeSimpleSsoAuthBundle:TrustedSso:login
                logout_action: false #BeSimpleSsoAuthBundle:TrustedSso:logout
                create_users: false
                created_users_roles: [ROLE_USER, ROLE_ADMIN]
#                default_target_path: index
                always_use_default_target_path: false
                login_path: /dashboard
                check_path: /
            logout:
                path: /logout

        #            logout:
        #                success_handler: security.logout.success_handler
        #            cas:
        #                cas_server: sso.dev.sictiam.fr
        #                cas_port: 443
        #                cas_path: /
        #                ca_cert_path: ~
        #                cas_protocol: '2.0'
        #                cas_mapping_attribute:
        #                check_path: /login_check
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    access_control:
        - { path: ^/doc/uploadfile, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/doc/notifymodif, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/doc/downloadJWS, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc/uploaddocument, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/classeur/valider_classeur_jws, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/classeur/liste-classeurs-admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/classeur/liste_admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/delegation, roles: ROLE_USER }
        - { path: ^/apirest, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/apirest/users/isauthenticated, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/collectivite, roles: ROLE_SUPER_ADMIN }
        - { path: ^/mailing, roles: ROLE_SUPER_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/circuit, roles: ROLE_USER }
        - { path: ^/classeur, roles: ROLE_USER }
        - { path: ^/doc, roles: ROLE_USER }
        - { path: ^/preferences/message, roles: ROLE_ADMIN }
        - { path: ^/preferences/notifications, roles: ROLE_ADMIN }
