<?php

namespace Sesile\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatchRepository extends EntityRepository
{
    public function uploadFile($file, $path, $dirPath) {

        if ($file) {
            if ($path->getPath()) {
                $this->removeUpload($dirPath . $path->getPath());
            }
            $fileName = sha1(uniqid(mt_rand(), true)) . '.' . $file->guessExtension();
            $path->setPath($fileName);
            $file->move(
                $dirPath,
                $fileName
            );
        }
        return $path;
    }


    public function removeUpload($file) {

        if (is_file($file)) {
            unlink($file);
        }
    }
}
