<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140116141559 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Groupe (id INT AUTO_INCREMENT NOT NULL, Nom VARCHAR(255) NOT NULL, Collectivite VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE UserHierarchie (id INT AUTO_INCREMENT NOT NULL, UserId VARCHAR(255) NOT NULL, ParentId VARCHAR(255) NOT NULL, GroupeId VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE User (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, Nom VARCHAR(255) NOT NULL, Prenom VARCHAR(255) NOT NULL, path VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(6) DEFAULT NULL, pays VARCHAR(255) DEFAULT NULL, departement VARCHAR(255) DEFAULT NULL, role VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_2DA1797792FC23A8 (username_canonical), UNIQUE INDEX UNIQ_2DA17977A0D96FBF (email_canonical), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Classeur (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, creation DATETIME NOT NULL, validation DATETIME NOT NULL, type VARCHAR(255) NOT NULL, status INT NOT NULL, user INT NOT NULL, validant INT NOT NULL, visibilite INT NOT NULL, circuit VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ClasseursUsers (classeur_id INT NOT NULL, user_id INT NOT NULL, ordre INT NOT NULL, INDEX IDX_A6067AC4EC10E96A (classeur_id), INDEX IDX_A6067AC4A76ED395 (user_id), PRIMARY KEY(classeur_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Document (id INT AUTO_INCREMENT NOT NULL, classeur_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, repourl VARCHAR(1000) NOT NULL, type VARCHAR(255) NOT NULL, signed TINYINT(1) NOT NULL, INDEX IDX_211FE820EC10E96A (classeur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE DocumentHistory (id INT AUTO_INCREMENT NOT NULL, document_id INT DEFAULT NULL, sha VARCHAR(255) DEFAULT NULL, date DATETIME NOT NULL, comment VARCHAR(1000) NOT NULL, INDEX IDX_279321ACC33F7837 (document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Circuit (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, user_id INT NOT NULL, ordre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Delegations (id INT AUTO_INCREMENT NOT NULL, delegant INT DEFAULT NULL, user INT DEFAULT NULL, debut DATE NOT NULL, fin DATE NOT NULL, INDEX IDX_AEB8727A851BB8D7 (delegant), INDEX IDX_AEB8727A8D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ClasseursUsers ADD CONSTRAINT FK_A6067AC4EC10E96A FOREIGN KEY (classeur_id) REFERENCES Classeur (id)");
        $this->addSql("ALTER TABLE ClasseursUsers ADD CONSTRAINT FK_A6067AC4A76ED395 FOREIGN KEY (user_id) REFERENCES User (id)");
        $this->addSql("ALTER TABLE Document ADD CONSTRAINT FK_211FE820EC10E96A FOREIGN KEY (classeur_id) REFERENCES Classeur (id)");
        $this->addSql("ALTER TABLE DocumentHistory ADD CONSTRAINT FK_279321ACC33F7837 FOREIGN KEY (document_id) REFERENCES Document (id)");
        $this->addSql("ALTER TABLE Delegations ADD CONSTRAINT FK_AEB8727A851BB8D7 FOREIGN KEY (delegant) REFERENCES User (id)");
        $this->addSql("ALTER TABLE Delegations ADD CONSTRAINT FK_AEB8727A8D93D649 FOREIGN KEY (user) REFERENCES User (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ClasseursUsers DROP FOREIGN KEY FK_A6067AC4A76ED395");
        $this->addSql("ALTER TABLE Delegations DROP FOREIGN KEY FK_AEB8727A851BB8D7");
        $this->addSql("ALTER TABLE Delegations DROP FOREIGN KEY FK_AEB8727A8D93D649");
        $this->addSql("ALTER TABLE ClasseursUsers DROP FOREIGN KEY FK_A6067AC4EC10E96A");
        $this->addSql("ALTER TABLE Document DROP FOREIGN KEY FK_211FE820EC10E96A");
        $this->addSql("ALTER TABLE DocumentHistory DROP FOREIGN KEY FK_279321ACC33F7837");
        $this->addSql("DROP TABLE Groupe");
        $this->addSql("DROP TABLE UserHierarchie");
        $this->addSql("DROP TABLE User");
        $this->addSql("DROP TABLE Classeur");
        $this->addSql("DROP TABLE ClasseursUsers");
        $this->addSql("DROP TABLE Document");
        $this->addSql("DROP TABLE DocumentHistory");
        $this->addSql("DROP TABLE Circuit");
        $this->addSql("DROP TABLE Delegations");
    }
}
