<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140313114800 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE classeur_groupe (type_classeur_id INT NOT NULL, groupe_id INT NOT NULL, INDEX IDX_C6A03DCBA7093EFB (type_classeur_id), INDEX IDX_C6A03DCB7A45358C (groupe_id), PRIMARY KEY(type_classeur_id, groupe_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE classeur_groupe ADD CONSTRAINT FK_C6A03DCBA7093EFB FOREIGN KEY (type_classeur_id) REFERENCES TypeClasseur (id)");
        $this->addSql("ALTER TABLE classeur_groupe ADD CONSTRAINT FK_C6A03DCB7A45358C FOREIGN KEY (groupe_id) REFERENCES Groupe (id)");
        $this->addSql("ALTER TABLE TypeClasseur DROP template");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE classeur_groupe");
        $this->addSql("ALTER TABLE TypeClasseur ADD template VARCHAR(255) NOT NULL");
    }
}
