<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140116171033 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE ClasseurUsers");
        $this->addSql("ALTER TABLE Action DROP FOREIGN KEY FK_406089A4D15F835A");
        $this->addSql("DROP INDEX IDX_406089A4D15F835A ON Action");
        $this->addSql("ALTER TABLE Action CHANGE classeur classeur_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Action ADD CONSTRAINT FK_406089A4EC10E96A FOREIGN KEY (classeur_id) REFERENCES Classeur (id)");
        $this->addSql("CREATE INDEX IDX_406089A4EC10E96A ON Action (classeur_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE ClasseurUsers (id INT AUTO_INCREMENT NOT NULL, classeur_id INT NOT NULL, userId INT NOT NULL, ordre INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Action DROP FOREIGN KEY FK_406089A4EC10E96A");
        $this->addSql("DROP INDEX IDX_406089A4EC10E96A ON Action");
        $this->addSql("ALTER TABLE Action CHANGE classeur_id classeur INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Action ADD CONSTRAINT FK_406089A4D15F835A FOREIGN KEY (classeur) REFERENCES Classeur (id)");
        $this->addSql("CREATE INDEX IDX_406089A4D15F835A ON Action (classeur)");
    }
}
