<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140116163318 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE Action (id INT AUTO_INCREMENT NOT NULL, classeur INT DEFAULT NULL, user INT DEFAULT NULL, username VARCHAR(255) NOT NULL, date DATETIME NOT NULL, action LONGTEXT NOT NULL, INDEX IDX_406089A4D15F835A (classeur), INDEX IDX_406089A48D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ClasseurUsers (id INT AUTO_INCREMENT NOT NULL, classeur_id INT NOT NULL, userId INT NOT NULL, ordre INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Action ADD CONSTRAINT FK_406089A4D15F835A FOREIGN KEY (classeur) REFERENCES Classeur (id)");
        $this->addSql("ALTER TABLE Action ADD CONSTRAINT FK_406089A48D93D649 FOREIGN KEY (user) REFERENCES User (id)");
        $this->addSql("ALTER TABLE DocumentHistory DROP FOREIGN KEY FK_279321ACC33F7837");
        $this->addSql("ALTER TABLE DocumentHistory ADD CONSTRAINT FK_279321ACC33F7837 FOREIGN KEY (document_id) REFERENCES Document (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Document DROP FOREIGN KEY FK_211FE820EC10E96A");
        $this->addSql("ALTER TABLE Document ADD CONSTRAINT FK_211FE820EC10E96A FOREIGN KEY (classeur_id) REFERENCES Classeur (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Delegations DROP FOREIGN KEY FK_AEB8727A8D93D649");
        $this->addSql("ALTER TABLE Delegations DROP FOREIGN KEY FK_AEB8727A851BB8D7");
        $this->addSql("ALTER TABLE Delegations ADD CONSTRAINT FK_AEB8727A8D93D649 FOREIGN KEY (user) REFERENCES User (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Delegations ADD CONSTRAINT FK_AEB8727A851BB8D7 FOREIGN KEY (delegant) REFERENCES User (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE Action");
        $this->addSql("DROP TABLE ClasseurUsers");
        $this->addSql("ALTER TABLE Delegations DROP FOREIGN KEY FK_AEB8727A851BB8D7");
        $this->addSql("ALTER TABLE Delegations DROP FOREIGN KEY FK_AEB8727A8D93D649");
        $this->addSql("ALTER TABLE Delegations ADD CONSTRAINT FK_AEB8727A851BB8D7 FOREIGN KEY (delegant) REFERENCES User (id)");
        $this->addSql("ALTER TABLE Delegations ADD CONSTRAINT FK_AEB8727A8D93D649 FOREIGN KEY (user) REFERENCES User (id)");
        $this->addSql("ALTER TABLE Document DROP FOREIGN KEY FK_211FE820EC10E96A");
        $this->addSql("ALTER TABLE Document ADD CONSTRAINT FK_211FE820EC10E96A FOREIGN KEY (classeur_id) REFERENCES Classeur (id)");
        $this->addSql("ALTER TABLE DocumentHistory DROP FOREIGN KEY FK_279321ACC33F7837");
        $this->addSql("ALTER TABLE DocumentHistory ADD CONSTRAINT FK_279321ACC33F7837 FOREIGN KEY (document_id) REFERENCES Document (id)");
    }
}
