<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140119163129 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE Classeur DROP FOREIGN KEY FK_2829E10C988FE87D");
        $this->addSql("ALTER TABLE Classeur DROP FOREIGN KEY FK_2829E10C8D93D649");
        $this->addSql("DROP INDEX IDX_2829E10C8D93D649 ON Classeur");
        $this->addSql("DROP INDEX IDX_2829E10C988FE87D ON Classeur");
        $this->addSql("ALTER TABLE Classeur CHANGE validant validant INT NOT NULL, CHANGE user user INT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE Classeur CHANGE user user INT DEFAULT NULL, CHANGE validant validant INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Classeur ADD CONSTRAINT FK_2829E10C988FE87D FOREIGN KEY (validant) REFERENCES User (id)");
        $this->addSql("ALTER TABLE Classeur ADD CONSTRAINT FK_2829E10C8D93D649 FOREIGN KEY (user) REFERENCES User (id)");
        $this->addSql("CREATE INDEX IDX_2829E10C8D93D649 ON Classeur (user)");
        $this->addSql("CREATE INDEX IDX_2829E10C988FE87D ON Classeur (validant)");
    }
}
