<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140307141854 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE UserHierarchie ADD parent INT DEFAULT NULL, ADD groupe INT DEFAULT NULL, DROP ParentId, DROP GroupeId");
        $this->addSql("ALTER TABLE UserHierarchie ADD CONSTRAINT FK_5BC9CB3D3D8E604F FOREIGN KEY (parent) REFERENCES UserHierarchie (id)");
        $this->addSql("ALTER TABLE UserHierarchie ADD CONSTRAINT FK_5BC9CB3D4B98C21 FOREIGN KEY (groupe) REFERENCES Groupe (id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_5BC9CB3D3D8E604F ON UserHierarchie (parent)");
        $this->addSql("CREATE INDEX IDX_5BC9CB3D4B98C21 ON UserHierarchie (groupe)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE UserHierarchie DROP FOREIGN KEY FK_5BC9CB3D3D8E604F");
        $this->addSql("ALTER TABLE UserHierarchie DROP FOREIGN KEY FK_5BC9CB3D4B98C21");
        $this->addSql("DROP INDEX IDX_5BC9CB3D3D8E604F ON UserHierarchie");
        $this->addSql("DROP INDEX IDX_5BC9CB3D4B98C21 ON UserHierarchie");
        $this->addSql("ALTER TABLE UserHierarchie ADD ParentId VARCHAR(255) NOT NULL, ADD GroupeId VARCHAR(255) NOT NULL, DROP parent, DROP groupe");
    }
}
