<?php

namespace Sesile\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sesile\ClasseurBundle\Entity\Classeur;

/**
 * EtapeGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeGroupeRepository extends EntityRepository
{
    public function findByUsers($userId) {

        $circuits_id = array();

        /*
         * On recupere les etapes qui sont attribués a l utilisateur directement
         */
        $groupes_du_user = $this
            ->createQueryBuilder('c')
            ->leftJoin('c.users', 'u')
            ->where('u.id = :userid')
            ->setParameter('userid', $userId)
            ->getQuery()
            ->getResult();

        foreach($groupes_du_user as $group) {
            $circuits_id[] = $group->getGroupe()->getId();
        }

        /*
         * On recupere les etapes qui sont attribués a l utilisateur via un groupe
         */
        $etapesGroupe = $this->findAll();

        // Liste des etapes des SO
        foreach ($etapesGroupe as $etapeGroupe) {
            $userPacks = $etapeGroupe->getUserPacks();
            // Liste des UserPack connectes aux SO
            foreach ($userPacks as $userPack) {
                $users = $userPack->getUsers();
                // Liste des utilisateurs connectés aux aux userPack connectés aux SO
                foreach ($users as $user) {
                    // Si on trouve un utilisateur qui est l utilisateur courant, on enregistre l 'id du SO
                    if ($user->getId() == $userId) {
                        $circuits_id[] = $etapeGroupe->getGroupe()->getId();
                    }
                }
            }
        }

        // dedoublonnage des id
        $circuits_id = array_unique($circuits_id);

        // On retourne les id des services organisationels
        return $circuits_id;

    }

    public function isUserInEtape(EtapeGroupe $etapeGroupe, $userId) {
        foreach ($etapeGroupe->getUsers() as $user) {
            if ($user-> getId() === $userId) {
                return true;
            }
        }

        foreach ($etapeGroupe->getUserPacks() as $userPack) {
            foreach ($userPack->getUsers() as $user) {
                if ($user-> getId() === $userId) {
                    return true;
                }
            }
        }

        return false;
    }

/*    public function findByUsersTools( User $user) {

        return $this
            ->createQueryBuilder('c')
            ->leftJoin('c.usersTools', 'u')
            ->where('u.id = :userid')
            ->setParameter('userid', $user->getId())
            ->getQuery()
            ->getResult();
    }*/

    /**
     * deleteUserFromEtapeGroupes
     * Fonction qui supprime un user de tous les EtapeGroupes de l'univers
     *
     * @param $id
     */
    public function deleteUserFromEtapeGroupes($id){
        $em = $this->getEntityManager();

        // On récupère l'entity utilisateur à supprimer
        $entity = $em->getRepository('SesileUserBundle:User')->findOneById($id);
        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        // On récupère tous les EtapeGroupes
        $etapeGroupes = $em->getRepository('SesileUserBundle:EtapeGroupe')->findAll();

        // Pour chaque EtapeGroupe
        foreach($etapeGroupes as $etapeGroupe) {
            // On supprime l'utilisateur du EtapeClasseur (s'il y est)
            $etapeGroupe->removeUser($entity);
        }
    }
}
