<?php

namespace Sesile\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserHierarchieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHierarchieRepository extends EntityRepository
{
}
