<?php

namespace Sesile\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPackRepository extends EntityRepository
{

    /**
     * deleteUserFromUserPacks
     * Fonction qui supprime un user de tous les UserPacks de l'univers
     *
     * @param $id
     */
    public function deleteUserFromUserPacks($id) {
        $em = $this->getEntityManager();

        // On récupère l'entity utilisateur à supprimer
        $entity = $em->getRepository('SesileUserBundle:User')->findOneById($id);
        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        // On récupère tous les UserPacks
        $userPacks = $em->getRepository('SesileUserBundle:UserPack')->findAll();

        // Pour chaque UserPack
        foreach($userPacks as $userPack) {
            // On supprime l'utilisateur du UserPack (s'il y est)
            $userPack->removeUser($entity);
        }
    }

}
