services:
    collectivite.manager:
        class: Sesile\MainBundle\Manager\CollectiviteManager
        autowire: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'
    sesile.mailer:
        class: Sesile\MainBundle\Manager\SesileMailer
        autowire: false
        arguments:
            - '@mailer'
            - '@templating'
            - '%domain%'
            - '%email_sender_address%'
            - '@logger'