INSERT INTO Collectivite (id, nom, domain, image, message, active, textmailnew, textmailrefuse, textmailwalid, abscissesVisa, ordonneesVisa, abscissesSignature, ordonneesSignature, couleurVisa, titreVisa, pageSignature, deleteClasseurAfter)
VALUES (1, 'Sictiam', 'sictiam', '5fc346b1845dcddeb2d58f38847a57c46d3f447f.jpeg', '<p>Le parapheur &eacute;lectronique S.E.SI.LE, <strong>Syst&egrave;me Electronique de SIgnature LEgale</strong>, vous offre l&rsquo;opportunit&eacute; de d&eacute;poser vos fichiers afin de proc&eacute;der &agrave; leur validation selon des circuits d&eacute;finis mais &eacute;galement de les <strong>signer &eacute;lectroniquement</strong>.<br /><br />A noter : les flux <strong>PES</strong> peuvent &ecirc;tre sign&eacute;s via le parapheur en utilisant le format d&eacute;di&eacute; XaDES normalis&eacute; par la DGFIP<br /><br /></p>
<h4><u>MESSAGE D''ALERTE :</u></h4>
<p>Nous vous informons que la nouvelle mise &agrave; jour de <strong>Google Chrome (version 43)</strong> <strong>ne permet plus l&rsquo;authentification par un certificat &eacute;lectronique sur SESILE.</strong> <br /><br />N&eacute;anmoins, la <strong>signature d&rsquo;un flux PES&nbsp;</strong>reste et restera possible sur <strong>Google Chrome jusqu&rsquo;&agrave; la version 45</strong>. Au-del&agrave;, vous devrez n&eacute;cessairement utiliser un autre navigateur Internet (Mozilla Firefox, Internet Explorer). <br /><br />Nous nous tenons &agrave; votre disposition pour toutes questions compl&eacute;mentaires aux coordonn&eacute;es suivantes :<br />- T&eacute;l : 04 92 96 80 80<br />- Mail : demat@sictiam.fr<br /><br />Cordialement,<br /><br /><em>L''&eacute;quipe D&eacute;mat&eacute;rialisation</em><br /><br /><br /><br /><br /></p>', 1, '<p>Bonjour {{ validant }},<br /><br />Un nouveau classeur <strong>{{ titre_classeur }}</strong> vient d''&ecirc;tre d&eacute;pos&eacute; par {{ deposant }} <br /> <br /> Il convient de le valider avant le<strong> {{ date_limite | date(''d/m/Y'') }}</strong>.<br /><br />Vous pouvez visionner le classeur {{lien|raw}}.<br /><br /></p>', '<p>Bonjour {{ deposant }}, <br /><br />Le classeur {{ titre_classeur }} vient d''&ecirc;tre refus&eacute; par {{ validant }} pour le motif suivant: <br /> {{ motif }} <br /><br /> Vous devez y apporter les modifications n&eacute;cessaires avant de le soumettre &agrave; nouveau <br /> Vous pouvez visionner le classeur {{lien|raw}}<br /><br /></p>
<p>&nbsp;</p>', '<p>Bonjour {{ deposant }},<br /><br />Le classeur "{{ titre_classeur }}" vient d''&ecirc;tre <strong>valid&eacute; </strong>par {{ validant }} <br /> <br /> Vous pouvez visionner le classeur {{lien|raw}}.<br /><br /></p>', 10, 10, 123, 253, '#454545', 'VISE PAR :', 0, 180);

INSERT INTO Collectivite (id, nom, domain, image, message, active, textmailnew, textmailrefuse, textmailwalid, abscissesVisa, ordonneesVisa, abscissesSignature, ordonneesSignature, couleurVisa, titreVisa, pageSignature, deleteClasseurAfter)
VALUES (2, 'Département 06', 'departement06', '65f6cc09840f559021ba9230d7ddca37d486cc84.jpeg', '<h4><u>MESSAGE D''ALERTE :</u></h4>Nous vous informons que la nouvelle mise à jour de <b>Google Chrome (version 43)</b> <b>ne permet plus
l’authentification par un certificat électronique sur SESILE.</b>
<br><br>Néanmoins, la <b>signature d’un flux PES&nbsp;</b>reste et restera possible sur <b>Google Chrome jusqu’à la version 45</b>. Au-delà, vous devrez nécessairement utiliser un autre navigateur Internet (Mozilla Firefox, Internet Explorer).

<br><br>Nous nous tenons à votre disposition pour toutes questions complémentaires aux coordonnées suivantes :<br>- Tél : 04 92 96 80 80<br>- Mail : demat@sictiam.fr<br><br>Cordialement,<br><br><i>L''équipe Dématérialisation,</i><br><i>Audrey CAUVIN</i><br><br>', 0, 'Bonjour {{ validant }},<br><br>Un nouveau classeur<b> {{ titre_classeur }}</b> vient d''être déposé par {{ deposant }}<br><br>Il convient de le valider avant le <b>{{ date_limite | date(''d/m/Y'') }}</b>.<br><br>Vous pouvez visionner le classeur {{lien|raw}}<br><br><br><br>', 'Bonjour {{ deposant }},<br><br>Le classeur "{{ titre_classeur }}" vient d''être <b>refusé </b>par {{ validant }}<br><br>Vous devez y apporter les modifications nécessaires avant de le soumettre à nouveau<br><br>Vous pouvez visionner le classeur {{lien|raw}}<br>', 'Bonjour {{ deposant }},<br><br>Le classeur "{{ titre_classeur }}" vient d''être <b>validé </b>par {{ validant }}<br><br>Vous pouvez visionner le classeur {{lien|raw}}<br><br><br><br><br><br><br>', 10, 10, 123, 253, '#454545', 'VISE PAR', 0, 180);