services:
    sesile_migration.manager:
        class: Sesile\MigrationBundle\Manager\SesileMigrationManager
        arguments: ["@doctrine.orm.default_entity_manager", '@sesile.mailer' ,'%contact%', "@logger"]
    sesile.migrator:
        class: Sesile\MigrationBundle\Migrator\SesileMigrator
        arguments: ["@sesile_migration.manager", "@collectivite.manager", "@logger"]
        tags:
            - { name: monolog.logger, channel: migrator }
    sesile_user.migrator:
        class: Sesile\MigrationBundle\Migrator\OzwilloUserMigrator
        arguments: ["@guzzle.client", "@collectivite.manager", "%user_gateway%",  "@logger"]
        tags:
            - { name: monolog.logger, channel: migrator }
    guzzle.client:
        class: GuzzleHttp\Client