services:
    legacy.collectivity.manager:
        class: Sesile\MigrationBundle\Manager\LegacyCollectivityManager
        arguments: ["@legacy.collectivity.service", "@logger"]
    legacy.collectivity.service:
        class: Sesile\MigrationBundle\Service\LegacyCollectivityService
        arguments: ["@doctrine.dbal.legacy_connection"]
    collectivity.migrator:
        class: Sesile\MigrationBundle\Migrator\CollectivityMigrator
        arguments: ["@legacy.collectivity.service", "@collectivite.manager", "@logger"]
        tags:
            - { name: monolog.logger, channel: migrator }