<?php

namespace Sesile\CircuitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CircuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitRepository extends EntityRepository
{

}