parameters:
#    sesile_users.example.class: Sesile\UsersBundle\Example

services:
#    sesile_users.example:
#        class: %sesile_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
