<?php

namespace Sesile\ClasseurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @property  container
 */
class ActionRepository extends EntityRepository
{
    public function addDocumentAction ($document, $text, $user) {

        $em = $this->getEntityManager();
        $classeur = $document->getClasseur();

        $action = new Action();
        $action->setClasseur($classeur);
        $action->setUser($user);
        $action->setAction($text . " " . $document->getName());
        $em->persist($action);
        $em->flush();
    }
}
