<?php

namespace Sesile\ClasseurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @property  container
 */
class ActionRepository extends EntityRepository
{
    public function addDocumentAction ($classeur, $text, $observation = "", $commentaire = "", $user) {

        $em = $this->getEntityManager();
        $action = new Action();

        $action->setClasseur($classeur);
        $action->setAction($text);
        $action->setObservation($observation);
        $action->setCommentaire($commentaire);
        $action->setUser($user);

        $em->persist($action);
        $em->flush();

        return true;
    }
}
