<?php

namespace Sesile\ClasseurBundle\Entity;

use Doctrine\ORM\EntityRepository;
use phpDocumentor\Reflection\Types\Array_;
use Sesile\UserBundle\Entity\EtapeClasseur;
use Sesile\UserBundle\Entity\User;
/**
 * CallbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @property  container
 */
class CallbackRepository extends EntityRepository
{
    public function getEvent($idClasseur)
    {
        return $this->createQueryBuilder('q')
            ->select('q')
            ->from(Callback::class, 'c')
            ->where('q.classeurId = :id')
            ->setParameter('id', $idClasseur)
            ->getQuery()
            ->getResult();
    }
}