<?php

namespace Sesile\ClasseurBundle\Entity;

use Doctrine\ORM\EntityRepository;
use phpDocumentor\Reflection\Types\Array_;
use Sesile\UserBundle\Entity\EtapeClasseur;
use Sesile\UserBundle\Entity\User;
/**
 * CallbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @property  container
 */
class CallbackRepository extends EntityRepository
{
    public function getEvent($idClasseur)
    {
        return $this->createQueryBuilder('q')
            ->select('q')
            ->from(Callback::class, 'c')
            ->where('q.classeur_id = :id')
            ->setParameter('id', $idClasseur)
            ->getQuery()
            ->getArrayResult();
    }

    public function setEvents($idClasseur, $event, $url)
    {

        return $this
            ->createQueryBuilder('c')
            ->insert('Callback', 'c')
            ->set('c.classeur_id', '?')
            ->setParameter(0, $idClasseur)
            ->set('c.event', '?')
            ->setParameter(0, $event)
            ->set('c.url', '?')
            ->setParameter(0, $url)
            ->getQuery()
            ->getArrayResult();
    }
}