<?php

namespace Sesile\ClasseurBundle\Entity;

use Doctrine\ORM\EntityRepository;
use phpDocumentor\Reflection\Types\Array_;
use Sesile\UserBundle\Entity\EtapeClasseur;
use Sesile\UserBundle\Entity\User;
/**
 * CallbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @property  container
 */
class CallbackRepository extends EntityRepository
{
    public function getEvent($idClasseur)
    {
        return $this->createQueryBuilder('c')
            ->where('c.classeurId = :classeur')
            ->setParameter('classeur', $idClasseur)
            ->getQuery()
            ->getResult();
    }
}