<?php

namespace Sesile\ClasseurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClasseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseurRepository extends EntityRepository {

    /**
     *
     * @return int l'id du prochain validant dans le circuit. 0 si le circuit est terminé
     */
    public function getNextvalidant() {
        $circuit = explode(",", $this->getCircuit());
        $curr_validant = key($this->validant, $circuit);
        $next_validant = $curr_validant + 1;
        return ($next_validant <= count($circuit))?$circuit[$next_validant]:0;
    }
}
