<?php

namespace Sesile\ClasseurBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sesile\MainBundle\Entity\Collectivite;

/**
 * TypeClasseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeClasseurRepository extends EntityRepository
{
    public function addBasicClasseurTypesToNewCollectivite(Collectivite $collectivite) {
        $em = $this->getEntityManager();
        $types = ["Divers", "Helios", "Acte", "Marchés", "Convocation", "Courrier AR", "Document Urba", "Classique"];
        foreach ($types as $type) {
            $newType = new TypeClasseur();
            $newType->setNom($type);
            $newType->setCreation(new \DateTime());
            $newType->setSupprimable(0);
            $newType->setCollectivites($collectivite);

            $em->persist($newType);
        }

        $em->flush();
    }
}
